# ############################################################################################################# #
# +-----------------------------------------------------------------------------------------------------------+ #
# |                                                                                                           | #
# |         ████████╗ █████╗ ████████╗███████╗███╗   ███╗██╗███╗  ██╗ █████╗ ████████╗ █████╗ ██████╗         | #
# |         ╚══██╔══╝██╔══██╗╚══██╔══╝██╔════╝████╗ ████║██║████╗ ██║██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗        | #
# |            ██║   ██║  ██║   ██║   █████╗  ██╔████╔██║██║██╔██╗██║███████║   ██║   ██║  ██║██████╔╝        | #
# |            ██║   ██║  ██║   ██║   ██╔══╝  ██║╚██╔╝██║██║██║╚████║██╔══██║   ██║   ██║  ██║██╔══██╗        | #
# |            ██║   ╚█████╔╝   ██║   ███████╗██║ ╚═╝ ██║██║██║ ╚███║██║  ██║   ██║   ╚█████╔╝██║  ██║        | #
# |            ╚═╝    ╚════╝    ╚═╝   ╚══════╝╚═╝     ╚═╝╚═╝╚═╝  ╚══╝╚═╝  ╚═╝   ╚═╝    ╚════╝ ╚═╝  ╚═╝        | #
# |                                                                                                           | #
# |                    Youtube:    www.youtube.com/@davigamer1614                                             | #
# |                    Github:     https://github.com/Guayand0/Minecraft-Plugin-Toteminator                   | #
# |                                                                                                           | #
# +-----------------------------------------------------------------------------------------------------------+ #
# ############################################################################################################# #

# ############################################################################################################# #
# +-----------------------------------------------------------------------------------------------------------+ #
# |                                                                                                           | #
# |                                █████╗  █████╗ ███╗  ██╗███████╗██╗ ██████╗                                | #
# |                               ██╔══██╗██╔══██╗████╗ ██║██╔════╝██║██╔════╝                                | #
# |                               ██║  ╚═╝██║  ██║██╔██╗██║█████╗  ██║██║  ██╗                                | #
# |                               ██║  ██╗██║  ██║██║╚████║██╔══╝  ██║██║  ╚██╗                               | #
# |                               ╚█████╔╝╚█████╔╝██║ ╚███║██║     ██║╚██████╔╝                               | #
# |                                ╚════╝  ╚════╝ ╚═╝  ╚══╝╚═╝     ╚═╝ ╚═════╝                                | #
# |                                                                                                           | #
# +-----------------------------------------------------------------------------------------------------------+ #
# ############################################################################################################# #

config:

  # You can add a new language adding (language.yml) to lang folder
  # If you want to have support for more languages by default, send
  # the .yml file with the translations and the language via GitHub
  # https://github.com/Guayand0/Minecraft-Plugin-Toteminator/issues

  # Available default languages: en
  # English - en.yml
  message-language: en

  # Enable/Disable the toteminator function
  toteminator-use: true # (you need to use "/totem reload" to apply changes)

  # Enable/Disable the new version available message (update-message)
  update-checker: true

  # List of allowed worlds in which the plugin works
  allowed-worlds:
    - world
    - world_nether
    - world_the_end

